spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/running_pacer
    username: pacer
    password: pacer
  jpa:
    hibernate:
      ddl-auto: validate   # 일단 validate 추천
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
    org.flywaydb: info
